# Generated by Django 2.1.5 on 2019-01-17 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statut',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Statut',
        ),
    ]
