# Generated by Django 2.1.5 on 2019-01-17 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0005_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statut',
            name='profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='profile_app.Profile'),
        ),
    ]
