# Generated by Django 2.1.5 on 2019-01-17 15:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0006_auto_20190117_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=140)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('picture', models.ImageField(blank=True, upload_to='comment_pictures')),
                ('profile', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='profile_app.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='statut',
            name='picture',
            field=models.ImageField(blank=True, upload_to='statut_pictures'),
        ),
        migrations.AddField(
            model_name='comment',
            name='statut',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='profile_app.Statut'),
        ),
    ]
